services:
  game:
    networks:
      - game_network
    container_name: game
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: runner
    image: tic-tac-toe
    env_file:
      - ../.env.production
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - NEXT_TELEMETRY_DISABLED=1
    ports:
      - '3000:3000'
    restart: always
networks:
  game_network:
    driver: bridge
